# -*- coding: utf-8 -*-
"""Import Il2CppDumper script.json in IDA Pro 7.4 through 9.3."""

import json

import ida_auto
import ida_bytes
import ida_funcs
import ida_kernwin
import ida_name
import ida_nalt
import ida_segment


PROCESS_FIELDS = {
    "ScriptMethod",
    "ScriptString",
    "ScriptMetadata",
    "ScriptMetadataMethod",
    "Addresses",
}

IMAGE_BASE = ida_nalt.get_imagebase()
NAME_LIMIT = max(1, int(getattr(ida_name, "MAXNAMELEN", 512)) - 24)
NAME_FLAGS = ida_name.SN_NOWARN | ida_name.SN_NOCHECK
NAME_FLAGS |= getattr(ida_name, "SN_FORCE", 0)


def ea_from_rva(value):
    return IMAGE_BASE + int(value)


def is_mapped(ea):
    return ida_segment.getseg(ea) is not None


def safe_name(ea, value):
    if not is_mapped(ea):
        return False

    name = str(value or "").strip()
    if not name:
        return False

    name = name[:NAME_LIMIT]
    if ida_name.set_name(ea, name, NAME_FLAGS):
        return True

    # SN_FORCE is unavailable on some older IDAPython builds.
    suffix = "_{:X}".format(ea)
    return bool(
        ida_name.set_name(
            ea,
            name[: max(1, NAME_LIMIT - len(suffix))] + suffix,
            ida_name.SN_NOWARN | ida_name.SN_NOCHECK,
        )
    )


def make_function(start, end):
    if start >= end:
        return "skipped"

    segment = ida_segment.getseg(start)
    if segment is None:
        return "skipped"

    end = min(end, segment.end_ea)
    if start >= end:
        return "skipped"

    existing = ida_funcs.get_func(start)
    if existing is not None:
        return "existing" if existing.start_ea == start else "skipped"

    return "created" if ida_funcs.add_func(start, end) else "failed"


def set_comment(ea, text, repeatable):
    return is_mapped(ea) and bool(ida_bytes.set_cmt(ea, str(text), repeatable))


def load_json(path):
    with open(path, "r", encoding="utf-8-sig") as handle:
        return json.load(handle)


def main():
    ida_auto.auto_wait()
    path = ida_kernwin.ask_file(
        False,
        "*.json",
        "Select script.json generated by Il2CppDumper",
    )
    if not path:
        print("[IL2CPP] Cancelled.")
        return

    data = load_json(path)
    stats = {
        "functions_created": 0,
        "functions_existing": 0,
        "functions_skipped": 0,
        "functions_failed": 0,
        "methods_named": 0,
        "strings_named": 0,
        "metadata_named": 0,
        "metadata_methods_named": 0,
    }

    if "Addresses" in data and "Addresses" in PROCESS_FIELDS:
        addresses = sorted({int(value) for value in data["Addresses"] if int(value) > 0})
        for rva_start, rva_end in zip(addresses, addresses[1:]):
            result = make_function(ea_from_rva(rva_start), ea_from_rva(rva_end))
            stats["functions_" + result] += 1

    if "ScriptMethod" in data and "ScriptMethod" in PROCESS_FIELDS:
        for item in data["ScriptMethod"]:
            if safe_name(ea_from_rva(item["Address"]), item.get("Name", "")):
                stats["methods_named"] += 1

    if "ScriptString" in data and "ScriptString" in PROCESS_FIELDS:
        for index, item in enumerate(data["ScriptString"], start=1):
            ea = ea_from_rva(item["Address"])
            if safe_name(ea, "StringLiteral_{}".format(index)):
                set_comment(ea, item.get("Value", ""), True)
                stats["strings_named"] += 1

    if "ScriptMetadata" in data and "ScriptMetadata" in PROCESS_FIELDS:
        for item in data["ScriptMetadata"]:
            ea = ea_from_rva(item["Address"])
            name = item.get("Name", "")
            if safe_name(ea, name):
                set_comment(ea, name, True)
                stats["metadata_named"] += 1

    if "ScriptMetadataMethod" in data and "ScriptMetadataMethod" in PROCESS_FIELDS:
        for item in data["ScriptMetadataMethod"]:
            ea = ea_from_rva(item["Address"])
            name = item.get("Name", "")
            if safe_name(ea, name):
                set_comment(ea, name, True)
                set_comment(
                    ea,
                    "Method EA: 0x{:X}".format(ea_from_rva(item["MethodAddress"])),
                    False,
                )
                stats["metadata_methods_named"] += 1

    ida_auto.auto_wait()
    print("\n[IL2CPP] Import complete")
    print("[IL2CPP] Image base: 0x{:X}".format(IMAGE_BASE))
    print("[IL2CPP] Source: {}".format(path))
    for key, value in stats.items():
        print("[IL2CPP] {}: {}".format(key, value))


if __name__ == "__main__":
    main()
